# -*- coding: utf-8 -*-
"""Untitled76.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vW75khP-YMMQch_z7-073Bd7YVf_5XX_
"""

import pandas as pd
data_soil=pd.read_csv("SoilS.csv")

data_t=data_soil[data_soil['District']=='Thrissur']
data_k=data_soil[data_soil['District']=='Kottayam']
data_ka=data_soil[data_soil['District']=='Kannur']
data_ko=data_soil[data_soil['District']=='Kollam']

data_new=pd.concat([data_t,data_k,data_ka,data_ko],axis=0)

import matplotlib.pyplot as plt

data_new.boxplot(column='Soil_pH', by='District')

import seaborn as sns

ax = sns.boxplot(x="District", y="Soil_pH", data=data_new)

!pip install researchpy

import researchpy as rp
import scipy.stats as stats
import statsmodels.api as sm

sns.violinplot(x="District", y="Soil_pH", data=data_new)

rp.summary_cont(data_new['Soil_pH'].groupby(data_new['District']))

stats.f_oneway(data_new['Soil_pH'][data_new['District'] == 'Kannur'],
             data_new['Soil_pH'][data_new['District'] == 'Kollam'],data_new['Soil_pH'][data_new['District'] == 'Kottayam'],data_new['Soil_pH'][data_new['District'] == 'Thrissur'])

from statsmodels.stats.multicomp import pairwise_tukeyhsd
tuckey=pairwise_tukeyhsd(endog=data_new['Soil_pH'],groups=data_new['District'],alpha=0.05)

tuckey.plot_simultaneous()
plt.vlines(x='District',ymin=-0.5,ymax=0.5,color='red')
tuckey.summary()

ax = sns.boxplot(x="District", y="Soil_Mg", data=data_new)

stats.f_oneway(data_new['Soil_Mg'][data_new['District'] == 'Kannur'],
             data_new['Soil_Mg'][data_new['District'] == 'Kollam'],data_new['Soil_Mg'][data_new['District'] == 'Kottayam'],data_new['Soil_Mg'][data_new['District'] == 'Thrissur'])

from statsmodels.stats.multicomp import pairwise_tukeyhsd
tukey=pairwise_tukeyhsd(endog=data_new['Soil_Mg'],groups=data_new['District'],alpha=0.05)

tukey.plot_simultaneous()
plt.vlines(x='District',ymin=-0.5,ymax=0.5,color='red')
tukey.summary()